var games15 = [];
//Update Feb 28, 2021
games15.push({data: "CBFJKJKLLLKEBEFGMDJGLFKHJHJIIIIJHJKDNDKGDHEFFFGHDKDIEIDJEJEGIGIHHHHIGIGJFIDLEKELFKFLGKHMLHHLGLFNGNGMMIKMMMLKNJLG", win_b: false, game: "2211866", white: "David J Bush", black: "kspttw"});
games15.push({data: "AI.sKEKLDLIHDEDCCCDBCBGBCDCMGIEFCGDDBGDHEGDGBICJBLALBKBJAKAJDICIHGCNFLLBNDMDLCMBNBMCHBGHEJGGHHGDICGKJGIGIEFNDNEKDKDMGJ", win_b: true, game: "2185628", white: "Arek Kulczycki", black: "lazyplayer"});
games15.push({data: "HC.sLKIGNDLLKLKHEFEEGIHDJGEKIIIHJHMBMCMDGDHCGCHBDGGHFIGJHIJFEHJJHKFHKFKCGFEIHGHHKE", win_b: true, game: "2185629", white: "Arek Kulczycki", black: "Daniel Sepczuk"});
games15.push({data: "AOEDLDKLFJDMGKGLFLENDLCMCLBMFMHMFNGGHGJFMFLFFFHEIEGIHIHHJGIHFIGHGDEHKHJIKJKIMHLINIMKMJKKLJIK", win_b: false, game: "2185630", white: "lazyplayer", black: "HappyHippo"});
games15.push({data: "CBEKKJKLLKLLMKMLFJGGJFHMGLIHHHIKHJFNGNGMNKJMENFLELFKFMIFEHFIDJGJCLBNDMCKDKDIEIEGFGGEGFIDJIKGIEJDJELCMCLD", win_b: false, game: "2185631", white: "lazyplayer", black: "P_Guz"});
games15.push({data: "AE.sKJKLFJJFIFDNHLGKHJJEGGHKFLFKIIJJKHJKDLIEEGHDEDDFFEEKDKEJDJEHEIFHCJDHFIHFFGGHHGHHMIMKGJJGNDLFMFLG", win_b: false, game: "2185632", white: "Daniel Sepczuk", black: "David J Bush"});
games15.push({data: "CBEKLKLLKLJNMJNJIMJLJMGNHOKEBEGGHGIFHFIIIHHHIGHIKHKIJIILIKHLLILHHKGLJKJHLF", win_b: true, game: "2185633", white: "HappyHippo", black: "kspttw"});
games15.push({data: "AOEDLDKLLLLKDDDEFILBKFLCMENCBFFCFBCGDFCFBIAHHDHEGEGFEGFFIDIFJFIHFHGCDGFEJEHIGIIGNJJMJNMIOHLHKHIJJJKI", win_b: false, game: "2200178", white: "kspttw", black: "HappyHippo"});
games15.push({data: "CBDLLKLLKLKEBEFKBMDJGJHHMDKIFIFJGIFHEIEHDIDHGHGKIJFMCJHEIIJKHLIMGNIFLFKDLCKGKFMELEMCLDGMHMHKIKJGHFHIHJGDIEJCGGFCJFGOFOIGJEMBLB", win_b: true, game: "2202557", white: "lazyplayer", black: "Daniel Sepczuk"});
games15.push({data: "CBKLMLMMNLNMLMJNKNMKEKDFJFDNILIGJGIHHGGIFIIFGFGGHFGHEHFGEGIEHDEIFHELFKGLHKGKHIHJJIIIKIKDLDKELEKGLGLFNEMF", win_b: false, game: "2186211", white: "Daniel Sepczuk", black: "P_Guz"});
games15.push({data: "AIDLJILDHGHHJGJJGKIIHIIHFIEDGGFHGHFJGIHJGJHDIDHFGFHEIF", win_b: true, game: "2204755", white: "kspttw", black: "David J Bush"});
games15.push({data: "CBKLDLEHNGKENDMBMCNBLCMDNCJCLBMGLLLIBEGIBHCEFIGGFGFHHGGHDIDHCICDCFDEDFDKBLFJEKEJIHHFLHKF", win_b: false, game: "2204810", white: "Daniel Sepczuk", black: "kspttw"});
games15.push({data: "AJ.sFJKLLLLKLDIFJFHHGHGJDIEIDKGICIDJBKBJFIHEFGBNCLDMELFKEKEDFDHBHCFEEEFCDEDDIBIAJBKAGCGBKBFFCGENEMDNGLFMFLHNGNGMILHLJJIKJKMCKDHJIJHKIH", win_b: true, game: "2206924", white: "Arek Kulczycki", black: "David J Bush"});
games15.push({data: "AG.sJIKLGIEDKELBLCMBJCIBHDIDGDGCKAGLFLGKFJFKEKDMCLBNELENFMFNGMGNIMJNHOIFJEHMJKILJLJGIIHF", win_b: false, game: "2196947", white: "kspttw", black: "David J Bush"});
games15.push({data: "AEDLJIJKLHKEHFILHKIIGJHHFIGGHGGHEHEGFGGEDFFECHDHCIDICJDJBLBMCLCMDKFKJJGMHMHLLJLKMGNJELEKFLGKGLEJJFJHLFJDKGJCNDLEMCMFNG", win_b: true, game: "2188812", white: "P_Guz", black: "David J Bush"});
games15.push({data: "ADDLKJKLMIKEHGJKJJLIHKHIJFIJGIGJEKHHFLGHDIEFFHGGFFFE", win_b: false, game: "2191089", white: "lazyplayer", black: "David J Bush"});
games15.push({data: "CBKLLLLKEKFGBEHHBHCECFCDDEECFDGBHCJBIAGDGCDLELEEEDCGGHHGGGHECHDHGFFEHDGEDGFFEHEGCIDJJFIEKFIIJIJKJJJHHIIH", win_b: false, game: "2195354", white: "Arek Kulczycki", black: "kspttw"});
games15.push({data: "AO.sLKEDJFLLKLJNMMKNNKMKHGKDLEMCLCLDMJIEJDJECGDCEFHCGCFEHEHFGFGGFGFHCJCKDJEKBMDLFIEIBJDMBNALEJGKKINJIJHLILKFHI", win_b: true, game: "2195385", white: "Daniel Sepczuk", black: "Arek Kulczycki"});
games15.push({data: "CBDLKJKLMLMMNLMNLKJKJJJNIKGLHMKEIFHEGGFFJDIIFJFIGIHIFKHGIGHHJHJGMFIHNDMDNCMENELGMGLI", win_b: false, game: "2187218", white: "HappyHippo", black: "P_Guz"});

//Update July 14, 2021
games15.push({data: "KBKLMMJFNDMDEHFEIFEKJKIMDLDKGKIGEFGJMELENCMCNBLG", win_b: false, game: "2237276", white: "Daniel Sepczuk", black: "So Lost"});
games15.push({data: "LBKLEKEDCCKEFHGFJEHGBFEGBICHAHCIBJCJIGHIBKCLCKDMBNAMIKGIEJFLEMELGJHJGKGLMLHKJHJGIHJI", win_b: false, game: "2237353", white: "Daniel Sepczuk", black: "So Lost"});
games15.push({data: "AO.sDEKLGIEKLLLKCLDDEDDFCFCGFKHGIFHENBIHNGMGMHLHLINFJGJHIGHH", win_b: false, game: "2237429", white: "Daniel Sepczuk", black: "Arek Kulczycki"});
games15.push({data: "AG.sJILDDCEBCDDBIEBCGFIGHHHFIFHEJFIDKCKEJDHGKHJGKFKGMFLGNGLFMELENCNBMCMBLCJBLAKBLBNDMDMGNFMHNHMINIMJNJMKNKMLNLMNMMLNLMKNKLKMLLJMJKGN", win_b: false, game: "2237430", white: "lazyplayer", black: "David J Bush"});
games15.push({data: "AH.sKJKLLKLLMKMLFJEDHEIBJDGIIHHJGJHIJIIKJLKKJKKILILH", win_b: false, game: "2224464", white: "Daniel Sepczuk", black: "David J Bush"});
games15.push({data: "AD.sJFFCLKLLKLICECEDDHDLHCIBDDDEGCFBIAHBGBHAGAJHFEGIEIEGLHLGIHJEKELCKDJDGHJGIGGFCHFIFHKCMDLEDFCGDGEFEEDIEHHLFKEMGLGKHJ", win_b: true, game: "2214729", white: "lazyplayer", black: "Arek Kulczycki"});
games15.push({data: "AK.sEFEDDDECLCFJIGKLGJLBKCMBMCNBKBLAIBICIDFKCGGICLCKDKDJEJFH", win_b: false, game: "2231152", white: "Daniel Sepczuk", black: "David J Bush"});
games15.push({data: "OA.sLKFKLDIMDLCNEMFNENFIJHGLMIMCDEEDEEDCLCKFMELGNFNEMFMHNHNGIGJEIEIFGGJDFFJILIKHGIGHHGHHIIIJHJFJHKILIKKL", win_b: false, game: "2215779", white: "Arek Kulczycki", black: "HappyHippo"});
games15.push({data: "CB.sKELDEDGILKLMMMJHBLDIEIGFHIIGHFDNDMCNEM", win_b: true, game: "2232275", white: "So Lost", black: "Daniel Sepczuk"});
games15.push({data: "MBIGLKLMMMLNNMMKDEDDEDFILHINJNKFJGJFGHHIGIFKIHJEHHGGFHFGDHDNEIIIKHKGJH", win_b: true, game: "2232276", white: "So Lost", black: "Daniel Sepczuk"});
games15.push({data: "AG.sDEDDBCFCEDECNBKLLLLKEKMCHEFJGIGJJIHKIKIHNCIJEJFHEHFG", win_b: false, game: "2242356", white: "Daniel Sepczuk", black: "So Lost"});

//Updated Jan 21, 2022
games15.push({data: "CBDLLKKECFGIJFIHHIHHFJGKELEKFKFHLGKDHGGFFGGGMELFMFMCNBNCLCLDFIGHJDHEEIEHDIDH", win_b: false, game: "2261038", white: "lazyplayer", black: "Arek Kulczycki"});
games15.push({data: "CBKLEKDFCFDEBECGLLLKFIDNBNCMDMCNGGFMIKHDLDKEHEIDLEKFLFKGLGKHLHKIIEJDFEGEEGFFEFFGDIEHDHEICKCLDKHCGCHLILHKGMGHLJJKJLKKJJKJEMENGK", win_b: true, game: "2246293", white: "Daniel Sepczuk", black: "Arek Kulczycki"});
games15.push({data: "OD.sLKEDLDLLKLKELEKFLFKGLGKIMHLJKJLIKHJIJHIIHHGJBLCLIKFNHJHIFMFLDLFIEJEHNIMJOJNLNKKMMKJMIMJLKKILLNMLGM", win_b: true, game: "2272989", white: "Daniel Sepczuk", black: "lazyplayer"});
games15.push({data: "CBDLLKKEBEGILHIFBMEJCJCIBJGGNDNBMCMDNCLGMGNEMEMBDIBLDKDMEKFLGJFJFKJBEGDHEH", win_b: true, game: "2265792", white: "lazyplayer", black: "Daniel Sepczuk"});
games15.push({data: "AD.sEKKLMILDBCDLBMBBCBCAACABDBEAFBDKCKDJHHIMLLHGFFIGGHGGEHFDDDFEBFFMLKKMLMJIEMELCJ", win_b: true, game: "2241575", white: "Arek Kulczycki", black: "lazyplayer"});
games15.push({data: "CBKLLLLKBECEBFCDADDLBNBMCGFKELEKNJJMKNMINGOHLJMJNDMEGKIHKGIKHIHHGIGHEHFHDIEJIIJHKILIJIMDLH", win_b: true, game: "2260363", white: "Daniel Sepczuk", black: "shalev"});
games15.push({data: "AI.sKEKLEKEDHHLBNBJFKFJGJEIFDDDEFGGEHFIEHEICJDIDHDHCFDEFGDIICJGBFCFAFBGADBEBCEECCFDGBHCIDHCHDFEENHLGMGLHMFMHNGMIJIKGAJBJAKBKALBLAMBNBMDMAOANNIMJNJMLNMOKNLNKKJHKMKLLLKKKILLJHJIJGKDLCNCMCLDKCKEIDIFIGGFLGLHIGIGJEMELFKFJEJDJHBIH", win_b: false, game: "2218311", white: "Daniel Sepczuk", black: "lazyplayer"});

//Update April 9, 2023
games15.push({data: "AE.sCDKLLKLLEKKEIEGHFHFIDJDKCKEIDIEHDHEGDGEEEFCLEJELGLFMHKFNDLCNBNCMAMBLALBKAKBJAJBIAIBHAHBGAGBFAFBEAEBDADBBBCCBCCFBEBFACFGCFEHDHCGDJEGFHHKDJCGJIIIHHIIFJFIG", win_b: false, game: "2271789", white: "JKB", black: "So Lost"});
games15.push({data: "GCDLKJLDNDKKJKJEMDNBOBOAMCLCMBKILILHMFLLCKDMCMCLBLCNIIIJJIHLBMAOIMKGGGJJMHMGNGNFGKHIGJFJ", win_b: false, game: "2242249", white: "lazyplayer", black: "HappyHippo"});
games15.push({data: "MBDLKJKKLJLLJKIMLKKLMKMLHLGNHNHMJMJLNKNLFNLDNCMENFODFLGIFHEDCGDFDGGELEMDIEIHEGGJEKEJDKDJBKCIBHAJBIBJKGKHJHJI", win_b: false, game: "2342230", white: "Daniel Sepczuk", black: "HappyHippo"});
games15.push({data: "ALDMCMDLBNLDLKEDHGHHIGJEDDDENCLFMEJGMFLHNGMINJOHLIMHGEIHBFFIBJFGAHDI", win_b: false, game: "2277948", white: "lazyplayer", black: "Arek Kulczycki"});
games15.push({data: "OADLLKLLKLLJMJLCBLBMCLCMLHNBEFIFHGHFFGGIFIEDDEKMFKFJEJEKIHIGHHHJJIGGGHFHDIEHDHEEFEEGDGGDFDGBGEHDGCHBHCIBICJBKCLAMBLBMCLELDJE", win_b: false, game: "2278335", white: "lazyplayer", black: "HappyHippo"});
games15.push({data: "MBDLBNEDDDDEJIKLLLLKDKEKKGKEHFHLGKFMGMGLNJMKNKMMMLJMKNKJLIFKMJIFLELDNCMDNDMENEMFNFMHMINHMGLHIKKIEIEJDJBMCLCMILLGGHHIJFJEIGHGHHGGFGGFFFGD", win_b: false, game: "2319397", white: "Daniel Sepczuk", black: "shalev"});
games15.push({data: "CNEDKEKLCGEKLLLKCKEJDIFHDLEGFGEHIHFLELFKDGDHBIEMCIGCDDDEBFCCBEEBDBDCADBBCBBCABACFCHBEFFDECGAFBFAGBHAIKFFKHLC", win_b: false, game: "2320622", white: "Daniel Sepczuk", black: "HappyHippo"});
games15.push({data: "MBKLLLLKJLIGDEDLMFLFEKDDEDJMMKLGIMFHDHFIDJDIEHEIBJDMCKFL", win_b: false, game: "2322796", white: "lazyplayer", black: "Daniel Sepczuk"});
games15.push({data: "LC.sKEKLLLLKFJJFJHKFEFDNDLCNBNCMAMBKCKBLHIEDDDECCCDECGDBBCDCBFBECECDAFAEFFFMLGIMEMENGMHNGNGLHLHKIKIJJJJIKIKHLHMDKGFEGEHCIDHEHDKCJEIHII", win_b: true, game: "2356209", white: "Daniel Sepczuk", black: "HappyHippo"});
games15.push({data: "CBLDLKEKBEHHCLDMBNBMCMCKLHJEEJGGDHFFGHFHIFGDIEJDNCNBMCMBLCLBKCGIMENDMDLGKFJHKHKGIHJGNFLLMIJLMKMMNLNGMGMLKLJNJMINIMHNGMHMHLILIJ", win_b: true, game: "2291552", white: "lazyplayer", black: "Daniel Sepczuk"});
