var games11 = [];
//Update Feb 28, 2021
games11.push({data: "KA.sHDHIJIJHGIFGGFGGCHDHBJDGCGDFCFDDDEBICIFCHF", win_b: true, game: "2125980", white: "urmaul", black: "lazyplayer"});
games11.push({data: "CBDHFGHDGEGDJDHIHEIEIDEIIIGHCHCFKEJG", win_b: false, game: "2140371", white: "urmaul", black: "lazyplayer"});
games11.push({data: "EC.sHDGHHHHGEGFFFGGDEFHCFDFCGCHAFEFBJBIBID", win_b: true, game: "2173183", white: "kspttw", black: "Daniel Sepczuk"});
games11.push({data: "CBDHJDHDBHCEHGHIGIIBJBJCGEEEDEFCCHEJJIDGBGEIBJ", win_b: true, game: "2175317", white: "kspttw", black: "gzero_bot"});
games11.push({data: "FC.sGEGHHHGIIIHJIJHIIHHDGDGFHEIFHGHFEG", win_b: true, game: "2164387", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "FC.sGEGBJBFGEGFFDFEDJEHIJIHHIGJHIIIHFHGGEEGDFEHDFDGCFCFBECEBCCDCBECEBHAGBGBFCDDDIDHEHGGHHFGF", win_b: false, game: "2200019", white: "mootwo", black: "lazyplayer"});
games11.push({data: "ACGHHHGIIIHGJFGJIGIEJCJDHFHEBJFGCHDFBGCEBDBEDE", win_b: true, game: "2060773", white: "P_Guz", black: "shalev"});
games11.push({data: "JJEGDEDDGEGFHEHFIEIFBIDFCFBHDGEFCGFD", win_b: false, game: "2163335", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "IJ.sHDEDCGDJGIGFFFGJIEFGDHGECJ", win_b: true, game: "2175631", white: "kspttw", black: "gzero_bot"});
games11.push({data: "EC.sHDGEHEHFEGFHDGGFCGDICIBKBGAK", win_b: false, game: "2185882", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "CBHDBHBICHEHDHCJBJCIAJAKDIDJEIEJFIFJGIGJHIHJJIIIJHIHJGIGJFHFIDJBJEJDIEHCHEDFHGEE", win_b: false, game: "2146992", white: "mootwo", black: "lazyplayer"});
games11.push({data: "AK.sDHDCCCCDHDIBEEEFGFGCHBHCFCED", win_b: false, game: "2161328", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "JJ.sGEDHBJFDGHFGDFBI", win_b: false, game: "2163392", white: "gzero_bot", black: "Jose Maria Grau Ribas"});
games11.push({data: "JJHDBHDCCCDBCBCDJDIHGCFEEEIBICHCJBIDDEDGCGBICHCIDHDIEHEIFHFIHHGHIF", win_b: true, game: "2175713", white: "Force majeure", black: "gzero_bot"});
games11.push({data: "JJEDDDDEGEIHHHJBGD", win_b: true, game: "2175714", white: "Force majeure", black: "gzero_bot"});
games11.push({data: "JJHDEEDCBHBJJDIHIFGIICEFCICHHHHIGHFIEHFHFF", win_b: true, game: "2175715", white: "Force majeure", black: "gzero_bot"});
games11.push({data: "CBDHHGHHGHGIIGHDBHFGCHBJCICJDIDJEIEJIHFIFHIIHIGKJJIJKHJHKGJGKFJFKEJEKDJDKCJBJCHCIDCEIEHFIFFDDEEC", win_b: false, game: "2175716", white: "gzero_bot", black: "Force majeure"});
games11.push({data: "FJGGDEEDEEFDDDDGBHCIAJECDCCFBEBF", win_b: false, game: "2175717", white: "gzero_bot", black: "Force majeure"});
games11.push({data: "JJEDDDHDDEDCCDECBDDHJDJCIDICFFFEEFCBDBDF", win_b: false, game: "2175718", white: "gzero_bot", black: "Force majeure"});
games11.push({data: "IJDCCCCDFDEGJG", win_b: true, game: "2175722", white: "kspttw", black: "gzero_bot"});
games11.push({data: "IJDHBHDCGEGBBCFDHBFIEFDJJGHFFG", win_b: true, game: "2175723", white: "kspttw", black: "gzero_bot"});
games11.push({data: "BBDHHGHHJDFIIGIHBJJBEHGCEFEGGFFGGHGIFHFEGDHCFDEEFFFCEDECCDBCDCEBCCCBDBDEICHDIBIDJCIFCG", win_b: true, game: "2175724", white: "kspttw", black: "gzero_bot"});
games11.push({data: "IJHDJDIGDEDDHGFHGFGICEGCIHHHDHEFCG", win_b: true, game: "2175725", white: "kspttw", black: "gzero_bot"});
games11.push({data: "AD.sHDGHHHHGEGIBFDEIDIDJCJEFDGDEIDFF", win_b: false, game: "2183935", white: "Arek Kulczycki", black: "lazyplayer"});
games11.push({data: "AD.sEGGHIEHDEDDIHHGFGEGDFHEJDFCHHGGGGI", win_b: true, game: "2183936", white: "lazyplayer", black: "Arek Kulczycki"});
games11.push({data: "ADDHHGHHGHGIFIGEBHEFCHED", win_b: false, game: "2175918", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AE.sDHHDICGHHHIDCFEF", win_b: false, game: "2175919", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AF.sDHGHBCBJHDGE", win_b: false, game: "2175920", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AHHDDEDDCEDHHGCBBCEI", win_b: false, game: "2175922", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AIBJHGHHIGIIJHIHJGIJGHHD", win_b: false, game: "2175923", white: "gzero_bot", black: "kspttw"});
games11.push({data: "FBDHHGHHGHGEEGEHDGFG", win_b: false, game: "2175924", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AGHDDHDGICHHIHIJIDEGJIIGFHHEBHDCCDBJCICBBCDEBFCCDDCJEIFJGIGKGJFKHJHKJHDKJJIIHIBGCGCHBIBECEAHCFECFD", win_b: true, game: "2175921", white: "gzero_bot", black: "kspttw"});
games11.push({data: "EBGHDHEFDEDF", win_b: false, game: "2175926", white: "gzero_bot", black: "kspttw"});
games11.push({data: "GBHDDEDFEFDJIHEEFEGGDHDI", win_b: false, game: "2175927", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AKGHDGDFEFDHCHFDCEEDBGDC", win_b: false, game: "2175928", white: "gzero_bot", black: "kspttw"});
games11.push({data: "CJGHDEDCCCCDIEHEIDHFEGFEIFHI", win_b: false, game: "2175929", white: "gzero_bot", black: "kspttw"});
games11.push({data: "AK.sCDCCHDGHHHIJIIHJJIJJGIHCFCEGEFEHDIEJCHDFDGCIDHCKBJBICJEEGDFEGFHEGEFFFI", win_b: true, game: "2206656", white: "Hekate", black: "Chrisek"});
games11.push({data: "ACHDIEHCCGFDJDJCEEDHEFDICJBI", win_b: false, game: "2204679", white: "mootwo", black: "Daniel Sepczuk"});
games11.push({data: "EC.sHDEIIHIJHJGEHEHFGFGHDIEHDHFF", win_b: false, game: "2176020", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "CBHDIHIIBHCJFHFJEHCIJGFE", win_b: false, game: "2176021", white: "mootwo", black: "kspttw"});
games11.push({data: "KA.sHDHIIIHJIJIHJFJHKGKHFGEHFHEJFJFIGIGHHHHGIGIEJCJEHFIFKDKEDJEIDHICIDJBHCDCCCDBCBCDBFAECGDEEFDIBJ", win_b: true, game: "2145311", white: "Daniel Sepczuk", black: "lazyplayer"});
games11.push({data: "KD.sHDHIDFDCCCCDBJCICHBIGIGEHGHFIEIFHEGFEFFHDIEJ", win_b: false, game: "2139167", white: "Daniel Sepczuk", black: "urmaul"});
games11.push({data: "CBGEHGDHEGHHIGIIEHFIJHJIIHGJFJGIBGDJJGCI", win_b: false, game: "2110559", white: "lazyplayer", black: "urmaul"});
games11.push({data: "EC.sHDHFDHGEIEIFJEFGFEGD", win_b: false, game: "2206830", white: "mootwo", black: "Daniel Sepczuk"});
games11.push({data: "KA.sHDEHDIDCCCDBBCCDDEICBFAEFCDGIHIICHEEECCGBIAHHGGDHCHFJEFHHEIF", win_b: false, game: "2215028", white: "Daniel Sepczuk", black: "Chrisek"});
games11.push({data: "CBDHIHIIHIHDBHBICHDGCIBGGEEEGDHCCGDEGCGFEFFFFEDFEGEHFGGHJGGJHGHJFI", win_b: true, game: "2161827", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "FCDHJDIIEHFFGFFGGHGGHGIEHFHDGEGDIGHBFEGAEB", win_b: true, game: "2161836", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "AG.sHDGHDHEDGFFGEFDGEGHBIBGEHEFFFDEEFEGDIGHIIIIHKGJHKHJJJIHKHJGKGJFKFJEKEJDKDJCKBJCJ", win_b: false, game: "2196663", white: "lazyplayer", black: "kspttw"});
games11.push({data: "CBHDCFDHIHFEDGCEBFBEICID", win_b: false, game: "2200846", white: "mootwo", black: "Daniel Sepczuk"});
games11.push({data: "CBGEHGHHIGIIGHFJEIFHDHDFJDEGJGJCIDICHDHCGDGCFDFCEDECCDGJFIDDCEDECGCFAGBGAHBH", win_b: false, game: "2163985", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "KA.sDEEDEEDCFDGBHCJBCEBDIAGDGCDHFGFF", win_b: false, game: "2163987", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "FC.sGEHDGDGGIHHHDH", win_b: true, game: "2161990", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "AG.sHDEGHGGHDFHIIIHJJIIHJFKGCHCIEHDHFGIBGF", win_b: true, game: "2188758", white: "Daniel Sepczuk", black: "kspttw"});
games11.push({data: "CBDHIHGEBHCDDGFDJDIBEDBJCGDIHEICFEFF", win_b: false, game: "2188804", white: "mootwo", black: "Daniel Sepczuk"});
games11.push({data: "CB.sEGHDDEDICHBJFHFGEHEJGIHJFKGHFI", win_b: true, game: "2100745", white: "shalev", black: "lazyplayer"});
games11.push({data: "AEDHHGHHIHHIIGIJJIIIJHJJFHHDGEGDFEFDDEEEDGDFBGBHCGEHBJCIGHFG", win_b: false, game: "2205202", white: "Chrisek", black: "Hekate"});
games11.push({data: "FC.sGEGGIHGHDHEFHEIDJB", win_b: true, game: "2164344", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "FC.sGEGHHHHDGDFGEFGIDH", win_b: true, game: "2164345", white: "Jose Maria Grau Ribas", black: "Daniel Sepczuk"});
games11.push({data: "KIHDCDDHJDCCBDBCDCHHBHEAFBDG", win_b: false, game: "2209406", white: "mootwo", black: "Daniel Sepczuk"});
games11.push({data: "BD.sBCHDCGCIBJCFGEGCEDBIFFEEFDGDFE", win_b: true, game: "2152122", white: "Daniel Sepczuk", black: "mootwo"});
games11.push({data: "BBGEHGHIIIIHGIEFCFCEDEGJDGDHEGEHFGFJBJCIBI", win_b: true, game: "2125582", white: "Daniel Sepczuk", black: "gzero_bot"});
games11.push({data: "KA.sDEDDEDEHHGHFIFIEFGHIGIEJCJGCBIFHGGHHGHFKJFGJIIJGIGIHDHDFCFCGAHBGAGBFAFBDBEECCDDBCCCBBCBBFCCEEFEE", win_b: false, game: "2125583", white: "gzero_bot", black: "mootwo"});
games11.push({data: "KD.sIHHDCDHIFJDHCHDGCGCIGECCBDBCDCGFHEIFFHHGEGEFFFGDFEED", win_b: false, game: "2211671", white: "Daniel Sepczuk", black: "lazyplayer"});
games11.push({data: "ACDHIHHDGEIIHIGDFEFDEEEDCECDDDECBEDCBDDECFDFCGDI", win_b: false, game: "2174868", white: "gzero_bot", black: "kspttw"});
games11.push({data: "EC.sHDGHHHGEIFIE", win_b: false, game: "2174869", white: "gzero_bot", black: "kspttw"});
games11.push({data: "FC.sFFGHHGHDDEEFGGFEIDHHBHEIDIBJCHDGBEAG", win_b: false, game: "2179013", white: "mootwo", black: "lazyplayer"});
games11.push({data: "ACDEHGHIIIHJIHIJGGHDFEFFEEGEDGEDHCDFEFDHEGEHFGGHFHEJAJCJBJCH", win_b: false, game: "1835060", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACDEHGHIDHGEFEGCEDEEFDEGDGEFGGGFFGFF", win_b: false, game: "1835271", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "AC.sHGIIEGFBDDGFEBEFFFFEGEHCGDGCFDECGBFCICJBIBHDIDFHDIDHEHHEDCEDDEEECG", win_b: true, game: "1852234", white: "Shumacher;", black: "shalev"});
games11.push({data: "ACHDCGCIFGFEDHCFEEDIEHEIGHGIFIEKFJFKIIHJGJGKJIHIIHFDEDHHIGHGIFHFIEHCICIDKCJBJCIB", win_b: false, game: "1852240", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACDHHGIHCIGIHIHHCHDGFHGEHDGGCGDEBFBECEDCCDCBDBCCDDFBECEBGCFCFDEDEFDFFG", win_b: true, game: "1754338", white: "Jos Dekker", black: "JKB"});
games11.push({data: "ACDEDFHIHHGECFCEHDGIJGJHIHHJFHDHCICHHEGG", win_b: false, game: "1836758", white: "Grzeniu", black: "Shumacher;"});
games11.push({data: "AC.sFFHIIEFHDHHCDDDEEEEFCGDFBFCEBECDBDCBCCEADBDAEBFAFBGAHBGBGCEHEGCJBJFEFCBGCFCHIIHJCIDGAIBHGEGDICHDJDHEHG", win_b: true, game: "1836760", white: "Shumacher;", black: "Force majeure"});
games11.push({data: "AC.sDHCIIHGHEDHEEGDIFHGIGGFCFD", win_b: true, game: "1836761", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "ACFFIHDEEEFGHEHFJEIGKFJFKEIDDFDHIEJGKGJHCGCHKHJIKIJKJJIKIJHKGJHJIIHIHHGIFHHDGEGDFEFCCD", win_b: true, game: "1836762", white: "Force majeure", black: "Shumacher;"});
games11.push({data: "ACGHIHIIDHBJEGEDFDHBFCEFHEFFIFGDJBGGFGGFHHIECGCFDFEE", win_b: false, game: "1918768", white: "shalev", black: "Force majeure"});
games11.push({data: "IB.sHDICCDCJIHIJHJGGEHEGFGGEHEGHJGIBDIGFFFFEDFDEBEDJFIECCFEFCH", win_b: true, game: "1820508", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "AC.sEDGEIHFGEGEFFFEEFEDICHGDFD", win_b: true, game: "1836951", white: "Tony", black: "Grzeniu"});
games11.push({data: "IBHIJIJHEGFEGEFFGFFGGGFHGHGDHDHCICFJFIEJDIEIDFEDBFBJBGCK", win_b: false, game: "1755164", white: "shalev", black: "wojtex"});
games11.push({data: "AD.sEGFCECEBFBEEHDGEHEGFHGHFJEIEJDJCIDHCICIBGDGCEDFDJBFHIG", win_b: true, game: "1804563", white: "Shumacher;", black: "lazyplayer"});
games11.push({data: "KI.sDEDHFHEDDDEEDFDGEFFGEHECGEEGHFGGHGGHHHGIHIGKGJFKFJEKDJ", win_b: true, game: "1770393", white: "Shumacher;", black: "Jose Maria Grau Ribas"});
games11.push({data: "ACHDEGEECFDHFGDGEFFCGDGEFEHBGBGCDFCEEDECDDDCCDCB", win_b: false, game: "1870422", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "AC.sHGHDFDEFGEFGHFGDFE", win_b: true, game: "1870429", white: "Shumacher;", black: "shalev"});
games11.push({data: "AC.sHGFDHDHEGEGGIDJBIBHIIHIEDH", win_b: true, game: "1903207", white: "urmaul", black: "shalev"});
games11.push({data: "IB.sHDGHIHICCDIIDHEICJFEGFHCEFEEDEDFGDGCFD", win_b: true, game: "1837719", white: "Force majeure", black: "Grzeniu"});
games11.push({data: "BBDEHDHIEGDIEIEHGGGFDGDJHGGHFHEJGIHH", win_b: false, game: "1837720", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACHDEGDEGDFFEFFEEEFCEDECFDHBGBGCBEDDCFBDICHCIDHEIEIGJFHHHFJA", win_b: false, game: "1829537", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "AC.sDHCIEDEFGFEJCHDIBIBJIHIJHHHGGHGGEHEEFFEGIE", win_b: true, game: "1862361", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "KH.sDEDCBCBDGGFIHHGJHJEGIJIHFGEHHIHGGHFFHEHDGEGDFEFDECEECGDFCFCI", win_b: false, game: "1829603", white: "shalev", black: "Shumacher;"});
games11.push({data: "AC.sHGHDJBHIIIHJIJHEEEEFFEGFFFEHFGGCFCEDDEDCFDFHGGHHDJGHDH", win_b: true, game: "1846376", white: "Tony", black: "shalev"});
games11.push({data: "AC.sHGIIDHCIGEEJGIHJFKGHHHHDGDHCGCGFIEHEIBJCEHEICHGGDIBJCK", win_b: true, game: "1854588", white: "Shumacher;", black: "Force majeure"});
games11.push({data: "ACDEHGHIIIHJIJIHJFJHGIHECGECGEGFEFHCGCFFFEEGBIBJCICJEHDIDH", win_b: true, game: "1854590", white: "Grzeniu", black: "shalev"});
games11.push({data: "BBDEGEHIFHGFEGFFEFFDFEHCICHD", win_b: false, game: "1830250", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACHIJIIJJJIFDHCIDIEFFFFEGEHCGDGBGCHBFCFBECEBBDEGFGEHFIFHHG", win_b: true, game: "1822262", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "IB.sHDICCDCCDHHCBDGDCGDIEHEIFHFIHICFEEEDDE", win_b: true, game: "1822264", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "AC.sEDGIIIHJJIHGDHEECFDECEDBDDCGDFDGFFEGFGEIGHHIIHHHEHGBGC", win_b: true, game: "1822265", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "ACDHGEGHHHGIIIGFCHDGCGCIAJCEBFBDCDBECFEEHEGDDEECEDGBFCFBICHBJCIDJFIJJIJEIEIFEFJDHDIAJBKAJABIAIAKBJCKBKFEFFDFFGEIHGHIIHHFGG", win_b: true, game: "1978111", white: "gzero_bot", black: "shalev"});
games11.push({data: "IB.sHDGFFFEHHGGGIEGIIHIIHIGKEJFJFHGHDG", win_b: true, game: "1830847", white: "Force majeure", black: "Grzeniu"});
games11.push({data: "ACGHIHHFEGFDHDGEDEDJDIEFCGCIDHCHDG", win_b: true, game: "1830849", white: "Force majeure", black: "Grzeniu"});
games11.push({data: "IB.sCDGHJDCBDBEIIFHGCIDJBJDGIGHIIIIHEHFGKGGJJHJEJGHDHEIEHFHCFE", win_b: true, game: "1871838", white: "shalev", black: "Grzeniu"});
games11.push({data: "ACHDEFDEFFFEEEFCHCGDEDECDDDCBDCDAFBEAEBFAGBGAHBHAIBJBIDIDHCICHFHEIEHGGGFHFFGHEGE", win_b: false, game: "1823010", white: "Grzeniu", black: "Shumacher;"});
games11.push({data: "BB.sHGHDFDFEDFEGCHDIBJEEDEECEDGCFCGADB", win_b: true, game: "1790605", white: "Shumacher;", black: "shalev"});
games11.push({data: "ACGHIHIJHJIGEGFDDEDDEDFBFCGBGCHBHCIBICJBECEBBDCCDB", win_b: true, game: "1856721", white: "Force majeure", black: "shalev"});
games11.push({data: "ACGHIHIJHJHDFEEGGFGGIEIFFGEIDIEHDGDHBICHBHBJCICGBGCEBDAFCFDEDF", win_b: true, game: "1873516", white: "Force majeure", black: "shalev"});
games11.push({data: "KI.sGJGECGEDDDDEBFDGCHDHCICEBECCCDEBECFBFCGBHCJBIBGCGDFDFEEFHFFFIDGH", win_b: false, game: "1832938", white: "Tony", black: "Shumacher;"});
games11.push({data: "ACEFDHHDGEFGCGCFDFEDFDFCGCEEDEDDCEBDDBDCHFHGGGFIGHGIIHHHJFIFJEIEJDIIFHEICJEHHI", win_b: true, game: "1841197", white: "Shumacher;", black: "Grzeniu"});
games11.push({data: "ACDEGEHIGHGFEGFFEFFEEEFCEDECDDDCCDCBFDGCGDIBHCHBCCDBBBBCADBDAEBEAFBFAGBGAHBHAIBJBIDIIGDHJBICJCIE", win_b: false, game: "1833020", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "BBDEHDHIGHGFFFFGCHDHDGCIAJBI", win_b: false, game: "1833211", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACHDDHCIIHEEJDIFCEEFDFCFDEDGBHCGAGCJCHEIFGBDBFEDDCGIGHGGFHFJJGHHKEIIHIGKJJJCID", win_b: true, game: "1833213", white: "Force majeure", black: "Grzeniu"});
games11.push({data: "BB.sHGHDFDFHDHCIDIEJCHEEFEEGDFEFDEECED", win_b: true, game: "1768506", white: "Shumacher;", black: "shalev"});
games11.push({data: "KG.sGHEDDCEGFGGEHEHDJCHCCECDBEFBDDCGCIDHJBIDJDIEJEIFCHEFKFJFKEIHKHJH", win_b: false, game: "1826155", white: "shalev", black: "Tony"});
games11.push({data: "ACDEHDGHIHIJEHGEFEGDEEFCEDECDDDCCDCBGCFDCCDBBBBCADBDAEBEAFBFAGBGAHBIBHCHHEFGGGFHHHHGJFIE", win_b: false, game: "1834641", white: "Grzeniu", black: "Force majeure"});
games11.push({data: "ACDEHGHIIIHJIJIHJFKGGIHDFEGCEDEEFDFFEFEGGEHFGFGGFGFHCIDIEHEIBI", win_b: true, game: "1834690", white: "Grzeniu", black: "shalev"});
games11.push({data: "AH.sJBHIJIJHDHBJGEFGCIEFDFDGBHCGBGCFBFCEBECDBDCBCCDBDCEBECFBHEFCGGFHGHFJFIEJ", win_b: false, game: "1810382", white: "shalev", black: "Shumacher;"});

//Update July 14, 2021
games11.push({data: "CBFFGHDEBEIECFCGEFEGHDGE", win_b: false, game: "2232067", white: "So Lost", black: "shalev"});
games11.push({data: "CBHDHGDHGEFGEGEHHFHEBIGHDGGF", win_b: false, game: "2242236", white: "Daniel Sepczuk", black: "lazyplayer"});
games11.push({data: "FC.sHDGHHHGIHIHGDHFEGFHCICJAJCGJEG", win_b: true, game: "2242354", white: "So Lost", black: "Daniel Sepczuk"});
games11.push({data: "CBFFIHIEBHDEHDEHGFGEHEGGFGFHEG", win_b: true, game: "2242355", white: "So Lost", black: "Daniel Sepczuk"});

//Updated Jan 21, 2022
games11.push({data: "CBHDHGDHBHFEEGDGJDJCCIBG", win_b: false, game: "2252957", white: "lazyplayer", black: "shalev"});
games11.push({data: "IBGHFHBJIHIIHIIGGFGEEFEJFIFJJGGGFGGDIE", win_b: true, game: "2261462", white: "shalev", black: "So Lost"});
games11.push({data: "FC.sGEGHHHHGEGEFJFEIDHFF", win_b: false, game: "2269721", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "CBHDDHDEJDJCIDICBEFEEEDGGEFFGDGG", win_b: false, game: "2270798", white: "Daniel Sepczuk", black: "shalev"});
games11.push({data: "DJHDJDJCDEDHCHDGCGCFBGDFBFDIBJCEBECCCDEBDCDBECFB", win_b: false, game: "2279075", white: "shalev", black: "So Lost"});
games11.push({data: "KIDHHDHGCIDCGFFHGHGGEHFGDFEGCHEEEFGEIEFDJFJGIGHIHHFJ", win_b: false, game: "2279101", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "CBGECFCEDEECBGEBHGFD", win_b: false, game: "2273669", white: "Daniel Sepczuk", black: "P_Guz"});
games11.push({data: "AK.sDHEDDDECCCDBCBDCCDDEBFDGHCFEGEIB", win_b: false, game: "2282339", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "AD.sEGHDFEDHIHHHBIHIJEDGIIHJIJIFKFJDIEGFEHFDDEDICJBHEEGBEB", win_b: true, game: "2282342", white: "Jose Maria Grau Ribas", black: "lazyplayer"});
games11.push({data: "ACDHHGHDGEHHGHGDFEFDEEEDCEDECFDFCGDIDGEGEFGFIEECJDHBBHCD", win_b: false, game: "2282343", white: "lazyplayer", black: "P_Guz"});
games11.push({data: "HBDHGGHHIFHFHGFIEHFGFHHDJEDIDEEJ", win_b: false, game: "2282349", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "CB.sDHHDGDEBECEFIFHC", win_b: false, game: "2282350", white: "P_Guz", black: "Daniel Sepczuk"});
games11.push({data: "CBHDJDDHBHDECEEFHEHIGHIBGEFDGDGCJBICJCEIIHFJGJGIIIHG", win_b: false, game: "2275611", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "CBHDHGDHCFFEJCJBICHCIBIEJFKDHEIDBIDIDGFG", win_b: false, game: "2284180", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "KD.sIHHDCDHIHHDHEGIIGIDDFEFJJHHCCEDEDG", win_b: true, game: "2260081", white: "Daniel Sepczuk", black: "lazyplayer"});
games11.push({data: "BB.sHGICEDFJDIEEHDHCGDFCGCHAJBHBGBGAEBDHDEHEJD", win_b: true, game: "2241925", white: "So Lost", black: "shalev"});
games11.push({data: "FCFFIHIIHIIGJGDEGF", win_b: true, game: "2269005", white: "So Lost", black: "Daniel Sepczuk"});
games11.push({data: "AK.sDEDHIDHIEHEGIIIHCHCIHGICHDGBJCHCJBJAFEDCCCDBCBFDHBIBDFGGFGFJGDDJEJGFJFGIFFEIFIFHGHEKDKIEKDKCJDKEJEIGIFGCCDEEEFCADACEDD", win_b: true, game: "2185881", white: "lazyplayer", black: "mootwo"});
games11.push({data: "AK.sDHEDDDECBCDEHCGFFEGBHFIAJAIBJBICJCIDBFGGJDIECGBGCFDIEHEIFHFIGHGIIHHHIGCHDGHGJEIIHIAAGJFKGKJFIF", win_b: true, game: "2221456", white: "lazyplayer", black: "Chrisek"});
games11.push({data: "EC.sGEFGIHICJBFDGDIGEFEIDHDGDJEGJEIJHGHHFHGGGHHFIFFJEHDICICJBJBKAKIDKCKBJCKDJD", win_b: true, game: "2192088", white: "lazyplayer", black: "Daniel Sepczuk"});

//Update April 9, 2023
games11.push({data: "ACDHHGHDGEGDFEFDEEEDCEHHIGIIGHFJBFEIBIEHCJBHJGGI", win_b: false, game: "2294309", white: "shalev", black: "P_Guz"});
games11.push({data: "IBDHHGHHGHGEHDHFBJFGCHCIBIDF", win_b: false, game: "2327425", white: "Daniel Sepczuk", black: "shalev"});
games11.push({data: "IBDHHGHIIIHDJCIEJFKDHEHJHHIJFIGIFHFGBIEHEJFECGBHCHDF", win_b: false, game: "2298820", white: "Daniel Sepczuk", black: "shalev"});
games11.push({data: "ACGEEGCIHDHIDHDIHHFH", win_b: false, game: "2332248", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "KA.sHDGHEHFFIHHIGIHHEFEGCHDGCGCJDICIDHDJFIFHEIDFCFDDDEEDEEGCIIIF", win_b: false, game: "2332524", white: "Jose Maria Grau Ribas", black: "Tony"});
games11.push({data: "CBDHHDHIEHGEBIDIHHGIFIFFCGEF", win_b: false, game: "2302649", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "IBGHHHHDJCIEJFGIKDHIJIJGHGIJDHEDFGGGGE", win_b: true, game: "2302650", white: "P_Guz", black: "Daniel Sepczuk"});
games11.push({data: "CBDHCFHDFGDECEDDCDDCBGEFDGBHEGDFCGFHEHDJEIEJGIFIGGGHIGHGIFHFJDIEJEJCIDICHEGFGE", win_b: true, game: "2302656", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "KD.sHDDCDHCJCHBIGIFJFIJBECGJEJEKDJCKIIHIIHHHIGHGIFHEICJDHFFF", win_b: false, game: "2303830", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "AI.sCDDHHGIIJBFJEHDIEJFIEIFFEGDEJGGEHE", win_b: true, game: "2304269", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "CBDHHGHHIIHDCFCEGEFICIDJBICGGHFGJGHF", win_b: false, game: "2337265", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "DBGHDHDGGGGECHDDDEEDEEFDCECCGDFEHEHDJCDCKBIDJDIEJEHGIFGI", win_b: false, game: "2273454", white: "P_Guz", black: "Jose Maria Grau Ribas"});
games11.push({data: "CBDHHGHHIGIHJGGIFHDIEJHDEGFEIDICDGDFBHBJ", win_b: false, game: "2273455", white: "P_Guz", black: "Jose Maria Grau Ribas"});
games11.push({data: "CBDHHGHHIGIHGHHDCFEIJFEJFJFEJC", win_b: true, game: "2273631", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "EC.sHDGHHHGFFFGIHIDJFIGJEJFG", win_b: false, game: "2273635", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "AD.sDHHIHDGEEFFDEDEBGDFEDCFCHEGFHFGGHHHGJFIGKGJI", win_b: false, game: "2307670", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "CB.sHDDJDIGEHEGGEGCJIFHIIIHJIJIHJFJHEJEIFIHHFHFGCIBJEHEDFEGDFDGBGCHBHCJA", win_b: false, game: "2280024", white: "So Lost", black: "P_Guz"});
games11.push({data: "CBGEHGHHDHEDCFEFHDGC", win_b: false, game: "2314630", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "AC.sHDGHIHIIHIIGJGEICIICEDEEIEJFHGHFIFHCFDHHDGCFFF", win_b: true, game: "2282356", white: "So Lost", black: "P_Guz"});
games11.push({data: "CBHDDHEFCFCGDFDGJDHEGEFG", win_b: false, game: "2282365", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "IB.sHDHIIIIHGIGEEGFDHEGFGDGJDIFEHF", win_b: true, game: "2315748", white: "Daniel Sepczuk", black: "shalev"});
games11.push({data: "KB.sHDGHIHIIBJDCEGCJHGGG", win_b: false, game: "2318198", white: "Daniel Sepczuk", black: "Jose Maria Grau Ribas"});
games11.push({data: "IB.sHDGEEGFIIHIGGGGCHEIBHBHCEDDCFBEHFG", win_b: true, game: "2318201", white: "Stanley Kozera", black: "Daniel Sepczuk"});
games11.push({data: "KB.sHHFFDEDCBCIIGGDJEHCBGEHDEFDFCDFEEEEGCHDGBGFBCCDBBBDDCEFHEI", win_b: true, game: "2318208", white: "Jose Maria Grau Ribas", black: "Stanley Kozera"});
games11.push({data: "KD.sIHEDHDIIHIGFFEGDGEEGDFIGJGGHIEGCBG", win_b: true, game: "2318237", white: "JKB", black: "lazyplayer"});
games11.push({data: "AK.sCDEGIHHIHHIICIDCDDCCBDBCJHJIECGBGCHBDGFAIBHCICHEHDFEJDIFHFFG", win_b: false, game: "2323893", white: "Daniel Sepczuk", black: "Tony"});
games11.push({data: "KC.sDEHDBJDCCDCIGEGHDICCBDCJIHGGFHEJFIBCFDFGCHEEEDCGDG", win_b: true, game: "2291189", white: "Jose Maria Grau Ribas", black: "P_Guz"});
games11.push({data: "ACDHHGHDGEFGHFHEGFHIIIHJIJIHJFJHBIBJCIEJ", win_b: false, game: "2291294", white: "lazyplayer", black: "Daniel Sepczuk"});
games11.push({data: "CB.sDHHIHDCJCHFEGF", win_b: true, game: "2324161", white: "Tony", black: "Jose Maria Grau Ribas"});
